#!/usr/bin/env sh

set -eu # exit on error, undefined variable

usage() {
  printf "Usage: lockon [OPTIONS] [COMMAND...]\n"
  printf "Options:\n"
  printf "  -a, --app-id ID    Target application ID (required if the command name is not the same as app_id)\n"
  printf "  -t, --threshold N  Seconds after which to spawn a new window instead of cycling (default: 60)\n"
  printf "  -h, --help         Show this help\n"
  exit "${1:-0}"
}

app_id=""
threshold=60
command_args=""

while [ $# -gt 0 ]; do
  skip=1
  case "$1" in
  -h | --help) usage ;;
  -a | --app-id)
    app_id="$2"
    skip=2
    ;;
  -t | --threshold)
    threshold="$2"
    skip=2
    ;;
  --)
    shift
    break
    ;;
  -*)
    printf "Unknown option: %s\n" "$1" >&2
    exit 1
    ;;
  *)
    break
    ;;
  esac
  shift "$skip"
done
if [ $# -eq 0 ]; then
  printf "Error: No command given.\n" >&2
  exit 1
fi

: "${app_id:=$1}"
: "${threshold:=1}" # default is 1 minute in seconds

if command -v niri >/dev/null 2>&1; then
  readonly WM=niri
else
  # may support other window managers in the future like hyprland, sway, etc. if the feature this script provides is not already built in
  if [ -t 1 ]; then
    printf "Current window manager is not supported.\n"
  else
    notify-send "Current window manager is not supported."
  fi
  exit 1
fi

case "$WM" in
niri)
  current_window=$(niri msg --json focused-window | jq --arg app_id "$app_id" 'if . and .app_id == $app_id then { id: .id, app_id: .app_id, focus_timestamp: .focus_timestamp.secs * 1e9 + .focus_timestamp.nanos } else null end')

  next_window_id=$(
    niri msg --json windows | jq --raw-output --argjson current_window "$current_window" --arg app_id "$app_id" --arg threshold "$threshold" '
      if $current_window then
        sort_by(.focus_timestamp.secs * 1e9 + .focus_timestamp.nanos)
        | reverse
        | first(.[] | select((.app_id == $app_id and $current_window.focus_timestamp - (.focus_timestamp.secs * 1e9 + .focus_timestamp.nanos)) > $threshold * 1e9))
        | .id // empty
      else
        # we havent started looping through the apps windows yet, so just find the most recently focused window
        sort_by(.focus_timestamp.secs * 1e9 + .focus_timestamp.nanos)
        | reverse
        | first(.[] | select(.app_id == $app_id))
        | .id // empty
      end
      '
  )
  if [ -n "$next_window_id" ]; then
    niri msg action focus-window --id "$next_window_id"
  else
    nohup "$@" &
  fi
  ;;
esac

exit 0
